
  <!-- Correct script tags for JS files -->
  <script src="<?= base_url('public/assets/js/auth-register.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/bootstrap-modal.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/bundle.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-chat-box.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-multiple-upload.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-statistic.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-table.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-user.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/custom.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/features-post-create.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/features-posts.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/features-setting-detail.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/forms-advanced-forms.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-advanced-route.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-draggable-marker.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-geocoding.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-geolocation.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-marker.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-multiple-marker.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-route.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-simple.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/index.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-calendar.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-chartjs.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-datatables.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-ion-icons.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-slider.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/slider.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-sparkline.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-sweetalert.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-toastr.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-vector-map.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/scripts.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/stisla.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/utilities-contact.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/jquery.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/jquery.min.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/jquery.min.map'); ?>"></script>
  <script src="<?= base_url('public/assets/js/jquery.slim.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/jquery.slim.min.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/jquery.slim.min.map'); ?>"></script>

  <script src="<?= base_url('public/assets/js/custom.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/isotope.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/isotope.min.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/lightbox.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/owl-carousel.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/slick-slider.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/tabs.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/video.js'); ?>"></script>
  